[package]
name = "rust_tutorial"
version = "0.1.0"
edition = "2021"
default-run = "3"

[dependencies]
rand = "0.8.5"

[[bin]]
name = "1"
path = "src/1.rs"

[[bin]]
name = "2"
path = "src/2.rs"

[[bin]]
name = "3"
path = "src/3.rs"
